name: Examples

on:
  push:
    branches: [main, next]
    paths:
      - "RelayPokedex/**"
      - "RelayStarWars/**"
      - "RelayTodo/**"
      - "Sources/Relay/**"
      - "Sources/RelaySwiftUI/**"
      - "Package.*"
  pull_request:
    branches: [main, next]
    paths:
      - "RelayPokedex/**"
      - "RelayStarWars/**"
      - "RelayTodo/**"
      - "Sources/Relay/**"
      - "Sources/RelaySwiftUI/**"
      - "Package.*"

jobs:
  build:
    name: Build ${{ matrix.scheme }} (Xcode ${{ matrix.xcode }})
    strategy:
      matrix:
        scheme:
          - RelayTodo
          - RelayStarWars
          - RelayPokedex
        xcode:
          - "13.2"
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: set -o pipefail && xcodebuild -scheme ${{ matrix.scheme }} -destination 'name=iPhone 11' | xcpretty
